"""
runtime_qa.py — RuntimeQAAgent
Verifies demo map load + actors via Unreal Editor scripting.
Writes RuntimeQAReport.json. Never fakes a pass.
"""

import json
import os
import time
import textwrap
from pathlib import Path

from app.core import ue_runner, config, logger as log


class RuntimeQAAgent:
    def __init__(self):
        self.name = "RuntimeQAAgent"

    # ------------------------------------------------------------------ #
    # Main entry point
    # ------------------------------------------------------------------ #
    def run(self, pack_name: str) -> dict:
        workspace = Path(config.WORKSPACE_ROOT) / pack_name
        reports_dir = workspace / "Reports"
        reports_dir.mkdir(parents=True, exist_ok=True)
        report_path = reports_dir / "RuntimeQAReport.json"

        log.info(f"[{self.name}] Starting runtime QA for '{pack_name}'")

        # Hard skip when Unreal is disabled — result is always a real failure
        if not config.BUILD_WITH_UNREAL:
            return self._write_report(
                report_path, pack_name,
                passed=False, skipped=True,
                map_loaded=False, actor_count=0,
                has_player_start=False, marker_found=False,
                error="BUILD_WITH_UNREAL=false", duration_s=0.0,
            )

        # Check prerequisite map-verify marker
        map_marker = workspace / "Markers" / "map_verified.marker"
        if not map_marker.exists():
            log.warning(f"[{self.name}] map_verified.marker missing — failing QA")
            return self._write_report(
                report_path, pack_name,
                passed=False, skipped=False,
                map_loaded=False, actor_count=0,
                has_player_start=False, marker_found=False,
                error="map_not_verified", duration_s=0.0,
            )

        # Marker for this QA run's results
        qa_marker_path = workspace / "Markers" / "runtime_qa.marker"
        qa_marker_path.parent.mkdir(parents=True, exist_ok=True)

        # Generate the Unreal Python script that runs inside the editor
        py_script = self._build_ue_python_script(pack_name, str(qa_marker_path))
        script_path = workspace / "Scripts" / "runtime_qa_check.py"
        script_path.parent.mkdir(parents=True, exist_ok=True)
        script_path.write_text(py_script)

        start = time.time()
        result = ue_runner.run_editor_cmd(script=str(script_path))
        duration = round(time.time() - start, 2)

        # Read the marker written by the UE Python script
        marker_data = {}
        marker_found = False
        if qa_marker_path.exists():
            try:
                marker_data = json.loads(qa_marker_path.read_text())
                marker_found = True
            except json.JSONDecodeError as exc:
                log.error(f"[{self.name}] Marker JSON invalid: {exc}")

        # Evaluate pass condition strictly
        load_ok = marker_data.get("load_ok", False)
        actor_count = marker_data.get("actor_count", 0)
        has_player_start = marker_data.get("has_player_start", False)

        # All three conditions must be true — no exceptions
        passed = marker_found and load_ok and actor_count > 0

        error_msg = None
        if result.returncode != 0:
            error_msg = f"Editor exited with code {result.returncode}"

        return self._write_report(
            report_path, pack_name,
            passed=passed, skipped=False,
            map_loaded=load_ok, actor_count=actor_count,
            has_player_start=has_player_start, marker_found=marker_found,
            error=error_msg, duration_s=duration,
        )

    # ------------------------------------------------------------------ #
    # Build Unreal Python script (runs inside editor process)
    # ------------------------------------------------------------------ #
    def _build_ue_python_script(self, pack_name: str, marker_path: str) -> str:
        # Use forward slashes inside UE Python to avoid escape issues
        marker_path_safe = marker_path.replace("\\", "/")
        return textwrap.dedent(f"""\
            # Auto-generated by RuntimeQAAgent — do not edit manually
            import unreal
            import json
            import os

            marker_path = r"{marker_path_safe}"

            result = {{
                "pack_name": "{pack_name}",
                "load_ok": False,
                "actor_count": 0,
                "has_player_start": False,
            }}

            try:
                # Load the demo map (expects a map named DemoMap inside content)
                asset_path = "/Game/{pack_name}/Maps/DemoMap"
                success = unreal.EditorLoadingAndSavingUtils.load_map(asset_path)
                result["load_ok"] = bool(success)

                if success:
                    # Count all actors currently in the world
                    actors = unreal.EditorLevelLibrary.get_all_level_actors()
                    result["actor_count"] = len(actors)

                    # Check for at least one PlayerStart
                    for actor in actors:
                        if isinstance(actor, unreal.PlayerStart):
                            result["has_player_start"] = True
                            break
            except Exception as exc:
                result["error"] = str(exc)

            # Write marker so the Python host process can read results
            os.makedirs(os.path.dirname(marker_path), exist_ok=True)
            with open(marker_path, "w") as fh:
                json.dump(result, fh, indent=2)

            print(f"[RuntimeQA] Marker written: {{marker_path}}")
        """)

    # ------------------------------------------------------------------ #
    # Write report and return standard dict
    # ------------------------------------------------------------------ #
    def _write_report(
        self, report_path: Path, pack_name: str,
        passed: bool, skipped: bool,
        map_loaded: bool, actor_count: int,
        has_player_start: bool, marker_found: bool,
        error, duration_s: float,
    ) -> dict:
        report = {
            "pack_name": pack_name,
            "passed": passed,
            "skipped": skipped,
            "map_loaded": map_loaded,
            "actor_count": actor_count,
            "has_player_start": has_player_start,
            "marker_found": marker_found,
            "error": error,
            "duration_s": duration_s,
        }
        report_path.write_text(json.dumps(report, indent=2))
        log.info(f"[{self.name}] QA passed={passed} — report written")
        return {"report_path": str(report_path), "passed": passed}
